/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CadencePicker: typeof import('./components/CadencePicker.vue')['default']
    CatalogIcon: typeof import('./components/CatalogIcon.vue')['default']
    CatalogPicker: typeof import('./components/CatalogPicker.vue')['default']
    DueSoonBanner: typeof import('./components/DueSoonBanner.vue')['default']
    FloatingAddButton: typeof import('./components/FloatingAddButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsDonut: typeof import('./components/StatsDonut.vue')['default']
    StatsTop: typeof import('./components/StatsTop.vue')['default']
    SubscriptionDetails: typeof import('./components/SubscriptionDetails.vue')['default']
    SubscriptionForm: typeof import('./components/SubscriptionForm.vue')['default']
    SubscriptionModal: typeof import('./components/SubscriptionModal.vue')['default']
    SubscriptionRow: typeof import('./components/SubscriptionRow.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    UpdatePrompt: typeof import('./components/UpdatePrompt.vue')['default']
  }
}
